/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Devices {
  activation_code: string | null;
  activation_expiry: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  name: string;
  secret_hash: string | null;
}

export interface DB {
  devices: Devices;
}
