type HttpErrorStatus = 400 | 401 | 403 | 404 | 409 | 410 | 422 | 429 | 500;

/**
 * Shape every HTTP error emitted by the fastify error handler serializes to.
 * Mirrors `ERROR_REPLY_SCHEMA` from `@scribear/base-schema`.
 */
interface ErrorReply {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

/**
 * Base class for application-thrown HTTP errors. Thrown from controllers and
 * services; the fastify error handler maps these to an `ErrorReply` response
 * with the configured status code.
 */
class BaseHttpError extends Error {
  readonly statusCode: HttpErrorStatus;
  readonly code: string;
  readonly details: Record<string, unknown> | undefined;

  /**
   * @param statusCode HTTP status code to send.
   * @param code Stable snake-case error code for the client to branch on.
   * @param message Human-readable summary.
   * @param details Optional per-error context (safe to expose to callers).
   */
  constructor(
    statusCode: HttpErrorStatus,
    code: string,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'BaseHttpError';
    this.statusCode = statusCode;
    this.code = code;
    this.details = details;
    if (Error.stackTraceLimit !== 0) {
      Error.captureStackTrace(this, BaseHttpError);
    }
  }
}

/**
 * Convenience constructors for the common HTTP error statuses. Each takes a
 * code/message/details triple and produces a `BaseHttpError` with the
 * corresponding status. Generic codes (`VALIDATION_ERROR`, `UNAUTHORIZED`,
 * `RATE_LIMITED`, `INTERNAL_ERROR`) are exposed as specialized helpers;
 * per-route statuses take any code string.
 */
const HttpError = {
  /**
   * 400 Bad Request. Usually generated by the schema validator; application
   * code rarely needs to throw this manually.
   */
  badRequest: (message: string, details?: Record<string, unknown>) =>
    new BaseHttpError(400, 'VALIDATION_ERROR', message, details),

  unauthorized: (message = 'Authentication required.') =>
    new BaseHttpError(401, 'UNAUTHORIZED', message),

  forbidden: (
    code: string,
    message: string,
    details?: Record<string, unknown>,
  ) => new BaseHttpError(403, code, message, details),

  notFound: (
    code: string,
    message: string,
    details?: Record<string, unknown>,
  ) => new BaseHttpError(404, code, message, details),

  gone: (code: string, message: string, details?: Record<string, unknown>) =>
    new BaseHttpError(410, code, message, details),

  conflict: (
    code: string,
    message: string,
    details?: Record<string, unknown>,
  ) => new BaseHttpError(409, code, message, details),

  unprocessable: (
    code: string,
    message: string,
    details?: Record<string, unknown>,
  ) => new BaseHttpError(422, code, message, details),

  rateLimited: (message = 'Rate limit exceeded.') =>
    new BaseHttpError(429, 'RATE_LIMITED', message),

  internal: (message = 'Server encountered an unexpected error.') =>
    new BaseHttpError(500, 'INTERNAL_ERROR', message),
};

export { BaseHttpError, HttpError };
export type { ErrorReply, HttpErrorStatus };
