import {
  BASE_ACCENT_COLOR,
  BASE_BACKGROUND_COLOR,
  BASE_TRANSCRIPTION_COLOR,
} from '@/config/base-theme';

import type { PresetThemeConfig } from '../types/theme';

export const PRESET_THEMES: PresetThemeConfig[] = [
  {
    id: 'default',
    name: 'Default',
    backgroundColor: BASE_BACKGROUND_COLOR,
    accentColor: BASE_ACCENT_COLOR,
    transcriptionColor: BASE_TRANSCRIPTION_COLOR,
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    backgroundColor: '#0f0f0f',
    accentColor: '#5c5c5c',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'vibrant-blue',
    name: 'Vibrant Blue',
    backgroundColor: '#281ffb',
    accentColor: '#42aad7',
    transcriptionColor: '#fcfc35',
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    backgroundColor: '#110c89',
    accentColor: '#42aad7',
    transcriptionColor: '#fcfc35',
  },
  {
    id: 'illinois',
    name: 'Illinois',
    backgroundColor: '#13294B',
    accentColor: '#e84a27',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'grape-soda',
    name: 'Grape Soda',
    backgroundColor: '#734f9a',
    accentColor: '#8bd450',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue',
    backgroundColor: '#3499cb',
    accentColor: '#e2af8d',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'sunset-red',
    name: 'Sunset Red',
    backgroundColor: '#ffa781',
    accentColor: '#c40a0a',
    transcriptionColor: '#5b0e2d',
  },
  {
    id: 'pitch-black',
    name: 'Pitch Black',
    backgroundColor: '#000000',
    accentColor: '#000000',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'dark-gray',
    name: 'Dark Gray',
    backgroundColor: '#5c5c5c',
    accentColor: '#1f1f1f',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'silver',
    name: 'Silver',
    backgroundColor: '#c2c2c2',
    accentColor: '#5c5c5c',
    transcriptionColor: '#000000',
  },
  {
    id: 'cloud-white',
    name: 'Cloud White',
    backgroundColor: '#ebebeb',
    accentColor: '#858585',
    transcriptionColor: '#000000',
  },
  {
    id: 'black-forest',
    name: 'Forest Black',
    backgroundColor: '#000000',
    accentColor: '#466636',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'rose-black',
    name: 'Rose Black',
    backgroundColor: '#000000',
    accentColor: '#995262',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'midnight-black',
    name: 'Midnight Black',
    backgroundColor: '#000000',
    accentColor: '#527399',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'black-royal',
    name: 'Royal Black',
    backgroundColor: '#000000',
    accentColor: '#705299',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'moss',
    name: 'Moss',
    backgroundColor: '#23331b',
    accentColor: '#466636',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'maroon',
    name: 'Maroon',
    backgroundColor: '#331b21',
    accentColor: '#995262',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'navy',
    name: 'Navy',
    backgroundColor: '#1b2633',
    accentColor: '#527399',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'plum',
    name: 'Plum',
    backgroundColor: '#251b33',
    accentColor: '#705299',
    transcriptionColor: '#ffffff',
  },
  {
    id: 'mint',
    name: 'Mint',
    backgroundColor: '#d7ffc4',
    accentColor: '#689952',
    transcriptionColor: '#000000',
  },
  {
    id: 'pink',
    name: 'Pink',
    backgroundColor: '#ffc4d1',
    accentColor: '#b35f72',
    transcriptionColor: '#000000',
  },
  {
    id: 'azure',
    name: 'Azure',
    backgroundColor: '#c4dfff',
    accentColor: '#5f86b3',
    transcriptionColor: '#000000',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    backgroundColor: '#ddc4ff',
    accentColor: '#835fb3',
    transcriptionColor: '#000000',
  },
  {
    id: 'wasabi',
    name: 'Wasabi',
    backgroundColor: '#f7fff3',
    accentColor: '#8bcc6d',
    transcriptionColor: '#000000',
  },
  {
    id: 'cherry',
    name: 'Cherry',
    backgroundColor: '#fff3f6',
    accentColor: '#ff88a3',
    transcriptionColor: '#000000',
  },
  {
    id: 'sky',
    name: 'Sky',
    backgroundColor: '#f3f9ff',
    accentColor: '#88bfff',
    transcriptionColor: '#000000',
  },
  {
    id: 'lilac',
    name: 'Lilac',
    backgroundColor: '#f8f3ff',
    accentColor: '#bb88ff',
    transcriptionColor: '#000000',
  },
];
