export enum KioskServiceStatus {
  INACTIVE = 'INACTIVE',

  NOT_REGISTERED = 'NOT_REGISTERED',
  REGISTERING = 'REGISTERING',
  REGISTRATION_ERROR = 'REGISTRATION_ERROR',

  IDLE = 'IDLE',
  ERROR = 'ERROR',

  SESSION_CONNECTING = 'SESSION_CONNECTING',
  SESSION_ERROR = 'SESSION_ERROR',
  ACTIVE = 'ACTIVE',
  ACTIVE_MUTE = 'ACTIVE_MUTE',
}
