/**
 * Reserved identities of the two seeded operator test-audio rooms, their source
 * devices, and their standing sessions.
 *
 * These exist so that the synthetic audio sources described in
 * `archived-plans/2026-07-27-01-PLAN-TestAudioDevices.md` need no hand
 * provisioning at all. The Session Manager seeds every row below under a
 * **fixed uid** when
 * `TEST_AUDIO_DEVICE_SECRET` is set (`TestAudioRoomsSeeder`), and the generator
 * derives its own credentials from the same secret and the same uids
 * ({@link deriveTestAudioDeviceToken}). Neither side is ever told a value the
 * other invented, which is what removes the copy-a-token-out-of-a-Set-Cookie-
 * header step this replaces.
 *
 * Every other room/device/session uid in the fleet is generated by the
 * database, so nothing but the seeder can ever hold these values.
 *
 * ---------------------------------------------------------------------------
 * THE ROOM ASSIGNMENT IS THE ENTIRE SAFETY BOUNDARY.
 *
 * A device token reaches **only its own device's room** — the endpoints it can
 * call (`my-schedule`, `get-my-room`, `exchange-device-token`) are all scoped to
 * the room the device is a member of, and it has no way to name another. So the
 * device-to-room assignment decides, permanently and by construction, which room
 * synthetic audio can ever reach. Putting one of these devices in a teaching
 * room would inject fixture speech into that lecture's LIVE CAPTIONS, silently,
 * with nothing in the stack to notice it.
 *
 * Fixing that assignment **in code** is stronger than an operator wiring it by
 * hand: there is no argument to point at the wrong room, no prompt to answer
 * wrongly at 2am, and re-running the seeder repairs a drifted assignment rather
 * than adding a second one. That is much of the point of seeding these.
 *
 * TWO ROOMS, NOT ONE: a room has exactly one source device and both devices must
 * be able to run at once, so they cannot share.
 * ---------------------------------------------------------------------------
 */

/** Reserved uid of the room the `good` synthetic source streams into. */
export const TEST_AUDIO_GOOD_ROOM_UID = 'deadbeef-0000-4000-8000-000000000011';
/** Reserved uid of the `good` synthetic source device. */
export const TEST_AUDIO_GOOD_DEVICE_UID =
  'deadbeef-0000-4000-8000-000000000012';
/** Reserved uid of the standing session in {@link TEST_AUDIO_GOOD_ROOM_UID}. */
export const TEST_AUDIO_GOOD_SESSION_UID =
  'deadbeef-0000-4000-8000-000000000013';

/** Reserved uid of the room the `fault` synthetic source streams into. */
export const TEST_AUDIO_FAULT_ROOM_UID = 'deadbeef-0000-4000-8000-000000000021';
/** Reserved uid of the `fault` synthetic source device. */
export const TEST_AUDIO_FAULT_DEVICE_UID =
  'deadbeef-0000-4000-8000-000000000022';
/** Reserved uid of the standing session in {@link TEST_AUDIO_FAULT_ROOM_UID}. */
export const TEST_AUDIO_FAULT_SESSION_UID =
  'deadbeef-0000-4000-8000-000000000023';

/**
 * The generator's two device ids, and the uid each one authenticates as.
 *
 * Keyed by the `deviceId` the generator's control API uses (`good` / `fault`)
 * so that neither side has to keep a second mapping in step.
 */
export const TEST_AUDIO_DEVICE_UIDS = {
  good: TEST_AUDIO_GOOD_DEVICE_UID,
  fault: TEST_AUDIO_FAULT_DEVICE_UID,
} as const;

/**
 * Display names of the seeded rooms.
 *
 * Chosen to read as unmistakably synthetic in the admin console's room list:
 * whoever is looking at a room called `TEST-AUDIO-GOOD` is not about to mistake
 * it for a lecture hall.
 */
export const TEST_AUDIO_GOOD_ROOM_NAME = 'TEST-AUDIO-GOOD';
export const TEST_AUDIO_FAULT_ROOM_NAME = 'TEST-AUDIO-FAULT';

/** Display names of the seeded source devices. */
export const TEST_AUDIO_GOOD_DEVICE_NAME = 'test-audio-good';
export const TEST_AUDIO_FAULT_DEVICE_NAME = 'test-audio-fault';
