/**
 * Reserved uid of the seeded demo caption room.
 *
 * The demo room is a purely *synthetic* caption source: the Node Server's
 * `DemoCaptionSource` publishes a looping fixture caption stream onto the demo
 * session's bus channel, and no audio is ever captured, sent, or transcribed
 * for it. The room therefore has no audio path at all — a device attached to it
 * can never do anything, and a device made its source actively misleads an
 * operator into expecting that device's audio to be transcribed.
 *
 * The Session Manager seeds the room under this fixed uid (`DemoRoomSeeder`,
 * `ON CONFLICT (uid) DO NOTHING`), which makes the uid a stable, well-known
 * marker: every other room uid is generated by the database, so nothing but the
 * demo room can ever hold this value.
 *
 * It lives in the shared schema package rather than inside one service because
 * it is part of the API contract, not an implementation detail: the Session
 * Manager refuses the room-management mutations that would attach a device to
 * it (`DEMO_ROOM_NOT_ASSIGNABLE`), and the admin console needs the same
 * identity to disable those controls before an operator discovers the rule by
 * hitting the error.
 */
export const DEMO_ROOM_UID = 'deadbeef-0000-4000-8000-000000000003';

/**
 * Reserved uid of the demo room's placeholder source device, seeded alongside
 * {@link DEMO_ROOM_UID} for the same reason (a fixed uid makes the insert a
 * genuine `ON CONFLICT (uid) DO NOTHING`, so restarts and racing instances
 * converge on one row).
 *
 * The device is a placeholder that is never activated and whose activation code
 * nobody holds, so it can never send audio for *any* room. Attaching it to a
 * real room is the mirror image of attaching a real device to the demo room and
 * is refused the same way (`DEMO_SOURCE_DEVICE_NOT_ASSIGNABLE`).
 */
export const DEMO_SOURCE_DEVICE_UID = 'deadbeef-0000-4000-8000-000000000002';
