import type { AppDependencies } from '#src/server/dependency-injection/app-dependencies.js';
import {
  DEMO_ROOM_UID,
  DEMO_SOURCE_DEVICE_UID,
} from '#src/server/features/demo-room/demo-room.constants.js';

// `Intl.supportedValuesOf('timeZone')` returns only canonical region zones
// (e.g. `America/New_York`) and omits aliases like `UTC` and `Etc/UTC` even
// though both are valid IANA identifiers accepted by Luxon. Constructing a
// DateTimeFormat throws RangeError for any unknown zone and accepts every
// alias the host's ICU database recognizes, so it's both more permissive and
// always in sync with the runtime.
function isValidTimezone(tz: string): boolean {
  try {
    new Intl.DateTimeFormat(undefined, { timeZone: tz });
    return true;
  } catch {
    return false;
  }
}

/**
 * The demo caption room is a purely synthetic emitter: the Node Server
 * publishes a looping fixture caption stream onto the demo session's bus
 * channel and no audio is ever captured or transcribed for it. So a device
 * attached to that room can never do anything, and a device made its *source*
 * is actively misleading — an operator would reasonably expect audio from it to
 * be transcribed, and it never will be.
 *
 * Both uids are literals reserved by the seeder, and every other room/device uid
 * is generated by the database, so these predicates cannot match a real room or
 * a real device. They are deliberately independent of `DEMO_ROOM_ENABLED`: the
 * uids stay reserved whether or not the seeder ran (a room seeded once and then
 * disabled is just as inert), and the answer should not depend on config the
 * caller cannot see.
 *
 * Callers run these *before* the existence lookups, so a request naming the
 * demo room gets the same specific refusal whether or not the room happens to
 * be seeded — rather than a 404 that invites the operator to try again once it
 * is.
 */
function isDemoRoom(roomUid: string): boolean {
  return roomUid === DEMO_ROOM_UID;
}

/**
 * The mirror image of {@link isDemoRoom}: the demo room's placeholder source
 * device is never activated and nobody holds its activation code, so it can
 * never send audio for *any* room. Putting it in a real room would leave that
 * room with a source that looks configured and is permanently silent, and would
 * also strand the demo room without a source on the next reseed.
 */
function isDemoSourceDevice(deviceUid: string): boolean {
  return deviceUid === DEMO_SOURCE_DEVICE_UID;
}

export class RoomManagementService {
  private _log: AppDependencies['logger'];
  private _roomManagementRepository: AppDependencies['roomManagementRepository'];
  private _deviceManagementRepository: AppDependencies['deviceManagementRepository'];

  constructor(
    logger: AppDependencies['logger'],
    roomManagementRepository: AppDependencies['roomManagementRepository'],
    deviceManagementRepository: AppDependencies['deviceManagementRepository'],
  ) {
    this._log = logger;
    this._roomManagementRepository = roomManagementRepository;
    this._deviceManagementRepository = deviceManagementRepository;
  }

  /**
   * Lists rooms with optional fuzzy search and cursor-based pagination.
   * @param params.search Fuzzy name filter using pg_trgm word similarity.
   * @param params.cursor Opaque cursor from a previous response's `nextCursor` field.
   * @param params.limit Maximum number of items to return.
   */
  async listRooms(params: {
    search: string | null;
    cursor: string | null;
    limit: number;
  }) {
    return this._roomManagementRepository.list(params);
  }

  /**
   * Fetches a single room by UID.
   * @param roomUid The room's unique identifier.
   * @returns The room, or `'ROOM_NOT_FOUND'` if no matching room exists.
   */
  async getRoom(roomUid: string) {
    const room = await this._roomManagementRepository.findById(roomUid);
    return room ?? 'ROOM_NOT_FOUND';
  }

  /**
   * Validates the timezone against the IANA list and requires exactly one source device.
   * The source device must not already belong to another room.
   * @param data.timezone Must be a valid IANA timezone identifier.
   * @param data.autoSessionEnabled Master switch for auto sessions in the room.
   * @param data.sourceDeviceUids Must contain exactly one UID; that device must not already be in a room, and must not be the demo room's placeholder source device.
   */
  async createRoom(data: {
    name: string;
    timezone: string;
    autoSessionEnabled: boolean;
    sourceDeviceUids: string[];
  }) {
    if (!isValidTimezone(data.timezone)) {
      return 'INVALID_TIMEZONE';
    }

    if (data.sourceDeviceUids.length > 1) {
      return 'TOO_MANY_SOURCE_DEVICES';
    }

    const sourceDeviceUid = data.sourceDeviceUids[0];
    if (sourceDeviceUid === undefined) {
      return 'NO_SOURCE_DEVICE';
    }

    // A created room can never *be* the demo room (its uid is generated by the
    // database), so the only demo-room state reachable from here is the
    // placeholder source device.
    if (isDemoSourceDevice(sourceDeviceUid)) {
      return 'DEMO_SOURCE_DEVICE_NOT_ASSIGNABLE';
    }

    const device =
      await this._deviceManagementRepository.findById(sourceDeviceUid);
    if (!device) {
      return 'DEVICE_NOT_FOUND';
    }
    if (device.roomUid !== null) {
      return 'DEVICE_ALREADY_IN_ROOM';
    }

    const room = await this._roomManagementRepository.create({
      name: data.name,
      timezone: data.timezone,
      autoSessionEnabled: data.autoSessionEnabled,
    });

    await this._roomManagementRepository.addDeviceToRoom(
      room.uid,
      sourceDeviceUid,
      true,
    );

    this._log.info({ roomUid: room.uid }, 'Room created');
    return room;
  }

  /**
   * Updates the name of a room.
   * @param roomUid The room to update.
   * @param data Fields to update; omit any field to leave it unchanged.
   * @returns The updated room, or `'ROOM_NOT_FOUND'`.
   */
  async updateRoom(roomUid: string, data: { name?: string }) {
    const room = await this._roomManagementRepository.update(roomUid, data);
    return room ?? 'ROOM_NOT_FOUND';
  }

  /**
   * Deletes a room by UID.
   * @param roomUid The room to delete.
   * @returns `undefined` on success, or `'ROOM_NOT_FOUND'` if the room does not exist.
   */
  async deleteRoom(roomUid: string) {
    const deleted = await this._roomManagementRepository.delete(roomUid);
    if (!deleted) return 'ROOM_NOT_FOUND';
    return;
  }

  /**
   * Adds a device to a room as either a source or non-source member.
   * @param params.roomUid The room to add the device to.
   * @param params.deviceUid The device to add; must not already be in a room.
   * @param params.asSource Whether to designate this device as the room's source.
   * @returns `undefined` on success, or an error code: `'DEMO_ROOM_NOT_ASSIGNABLE'`, `'DEMO_SOURCE_DEVICE_NOT_ASSIGNABLE'`, `'ROOM_NOT_FOUND'`, `'DEVICE_NOT_FOUND'`, or `'DEVICE_ALREADY_IN_ROOM'`.
   */
  async addDeviceToRoom(params: {
    roomUid: string;
    deviceUid: string;
    asSource: boolean;
  }) {
    if (isDemoRoom(params.roomUid)) return 'DEMO_ROOM_NOT_ASSIGNABLE';
    if (isDemoSourceDevice(params.deviceUid)) {
      return 'DEMO_SOURCE_DEVICE_NOT_ASSIGNABLE';
    }

    const [roomExists, device] = await Promise.all([
      this._roomManagementRepository.findRoomExists(params.roomUid),
      this._deviceManagementRepository.findById(params.deviceUid),
    ]);

    if (!roomExists) return 'ROOM_NOT_FOUND';
    if (!device) return 'DEVICE_NOT_FOUND';
    if (device.roomUid !== null) return 'DEVICE_ALREADY_IN_ROOM';

    await this._roomManagementRepository.addDeviceToRoom(
      params.roomUid,
      params.deviceUid,
      params.asSource,
    );
    return;
  }

  /**
   * Removes a device from whichever room it belongs to.
   * Deliberately *not* demo-room guarded: detaching only ever makes a room
   * emptier, so it cannot create the misleading state {@link isDemoRoom}
   * prevents, and it is the escape hatch an operator needs to clean up a device
   * attached to the demo room before those guards existed. The demo room's own
   * placeholder source is already refused here by the existing
   * `WOULD_LEAVE_ROOM_WITHOUT_SOURCE` rule, which is the accurate reason.
   * @param deviceUid The device to remove.
   * @returns `WOULD_LEAVE_ROOM_WITHOUT_SOURCE` if the device is the room's current source.
   */
  async removeDeviceFromRoom(deviceUid: string) {
    const membership =
      await this._roomManagementRepository.findRoomMembership(deviceUid);
    if (!membership) return 'MEMBERSHIP_NOT_FOUND';
    if (membership.is_source) return 'WOULD_LEAVE_ROOM_WITHOUT_SOURCE';

    await this._roomManagementRepository.removeDeviceFromRoom(deviceUid);
    return;
  }

  /**
   * Promotes a device to source within a room. The device must already be a member.
   * @param roomUid The room to update.
   * @param deviceUid The device to promote; must already be a member of the room.
   * @returns `DEVICE_NOT_IN_ROOM` if the device is not a current member, or a demo-room refusal code.
   */
  async setSourceDevice(roomUid: string, deviceUid: string) {
    if (isDemoRoom(roomUid)) return 'DEMO_ROOM_NOT_ASSIGNABLE';
    if (isDemoSourceDevice(deviceUid)) {
      return 'DEMO_SOURCE_DEVICE_NOT_ASSIGNABLE';
    }

    const roomExists =
      await this._roomManagementRepository.findRoomExists(roomUid);
    if (!roomExists) return 'ROOM_NOT_FOUND';

    const updated = await this._roomManagementRepository.setSourceDevice(
      roomUid,
      deviceUid,
    );
    if (!updated) return 'DEVICE_NOT_IN_ROOM';
    return;
  }

  /**
   * Returns the room a device belongs to, looked up by device UID.
   * @param deviceUid The authenticated device's unique identifier.
   * @returns The room, or `'DEVICE_NOT_IN_ROOM'` if the device is not a member of any room.
   */
  async getMyRoom(deviceUid: string) {
    const membership =
      await this._roomManagementRepository.findRoomMembership(deviceUid);
    if (!membership) return 'DEVICE_NOT_IN_ROOM';

    const room = await this._roomManagementRepository.findById(
      membership.room_uid,
    );
    if (!room) return 'DEVICE_NOT_IN_ROOM';

    return {
      uid: room.uid,
      name: room.name,
      timezone: room.timezone,
      roomScheduleVersion: room.roomScheduleVersion,
    };
  }
}
