/**
 * Reserved identities of the seeded monitoring canary room, its source device,
 * and its standing session.
 *
 * The synthetic canary (A2) streams a known recording into a real session every
 * few minutes and scores the captions that come back. Until now the device it
 * authenticated as was provisioned **by hand**: an operator registered a device
 * through the admin API, activated it, scraped `DEVICE_TOKEN` out of a
 * `Set-Cookie` header, pasted it into `.env` as
 * `MONITORING_CANARY_DEVICE_TOKEN`, then created a room, attached the device and
 * gave the room a session. Every one of those steps was a chance to point the
 * canary at the wrong room.
 *
 * Now the Session Manager seeds every row below under a **fixed uid** whenever
 * `CANARY_DEVICE_SECRET` is set (`CanaryRoomSeeder`), and the monitoring sidecar
 * derives its own credential from the same secret and the same uid
 * (`deriveTestAudioDeviceToken`, the one derivation every seeded synthetic
 * device shares). Neither side is ever told a value the other invented, so
 * there is nothing to copy and nothing to keep in step.
 *
 * Every other room/device/session uid in the fleet is generated by the
 * database, so nothing but the seeder can ever hold these values.
 *
 * ---------------------------------------------------------------------------
 * THE ROOM ASSIGNMENT IS THE ENTIRE SAFETY BOUNDARY.
 *
 * A device token reaches **only its own device's room** — `my-schedule`,
 * `get-my-room` and `exchange-device-token` are all scoped to the room the
 * device is a member of, and it has no way to name another. So the
 * device-to-room assignment decides, permanently and by construction, which
 * room the canary's fixture speech can ever reach. Putting this device in a
 * teaching room would inject that recording into the lecture's LIVE CAPTIONS,
 * silently, with nothing in the stack to notice it.
 *
 * Fixing that assignment **in code** is stronger than an operator wiring it by
 * hand: there is no argument to point at the wrong room, no `Set-Cookie` header
 * to misread, and re-running the seeder repairs a drifted assignment rather
 * than adding a second one. That is much of the point of seeding it.
 *
 * The canary is the sharpest case of this in the fleet, because it is the only
 * synthetic source that runs **unattended**. The two operator test-audio
 * devices stream when somebody presses go and watches a meter; the canary
 * starts on a timer every `CANARY_INTERVAL_SEC` with nobody looking. A
 * mis-assigned canary would not be noticed until someone read a transcript.
 * ---------------------------------------------------------------------------
 *
 * These are plain strings with no `node:crypto` in reach, so — unlike the
 * test-audio uids, which share a module with the derivation — they live in the
 * package index next to the demo room's reserved uids. A reserved uid is not a
 * secret; it is API contract, and the `@scribear/session-manager-schema/
 * test-audio` subpath exists for the node builtin, not for concealment.
 */

/** Reserved uid of the room the monitoring canary streams into. */
export const CANARY_ROOM_UID = 'deadbeef-0000-4000-8000-000000000031';

/** Reserved uid of the monitoring canary's source device. */
export const CANARY_DEVICE_UID = 'deadbeef-0000-4000-8000-000000000032';

/** Reserved uid of the standing session in {@link CANARY_ROOM_UID}. */
export const CANARY_SESSION_UID = 'deadbeef-0000-4000-8000-000000000033';

/**
 * Display name of the seeded canary room.
 *
 * Chosen to read as unmistakably synthetic in the admin console's room list, in
 * the same shape as `TEST-AUDIO-GOOD` / `TEST-AUDIO-FAULT`: whoever is looking
 * at a room called `MONITORING-CANARY` is not about to mistake it for a lecture
 * hall.
 */
export const CANARY_ROOM_NAME = 'MONITORING-CANARY';

/** Display name of the seeded canary source device. */
export const CANARY_DEVICE_NAME = 'monitoring-canary';
