name: "Setup Python"
description: "Checks out the repo and installs dependencies for python packages."
inputs:
  python-version:
    description: "Python version to use for setup."
    default: "3.12.11"
runs:
  using: "composite"

  steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "transcription_service/uv.lock"
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      working-directory: "transcription_service"
      shell: bash
      run: uv sync --frozen --extra dev --extra faster-whisper --extra silero-vad-cpu
