import fastifyPlugin from 'fastify-plugin';

import { BaseHttpError, type ErrorReply } from '../errors/http-errors.js';
import type {
  BaseFastifyInstance,
  BaseFastifyReply,
  BaseFastifyRequest,
} from '../types/base-fastify-types.js';

/**
 * Fixed code and message for HTTP statuses generated by the Fastify framework
 * (not thrown by application code). These bypass normal route logic, so the
 * error handler normalizes them into the canonical `ErrorReply` shape.
 */
const FRAMEWORK_ERRORS: Record<number, ErrorReply> = {
  405: { code: 'METHOD_NOT_ALLOWED', message: 'Method not allowed.' },
  406: { code: 'NOT_ACCEPTABLE', message: 'Not acceptable.' },
  415: { code: 'UNSUPPORTED_MEDIA_TYPE', message: 'Unsupported media type.' },
};

/**
 * Fastify error handler producing the canonical `ErrorReply` shape.
 *
 * - `BaseHttpError` subclasses are serialized with their configured status
 *   and carry the caller-supplied `code`, `message`, and `details`.
 * - Framework-generated 405/406/415 errors are normalized to a fixed code.
 * - Anything else is logged and returned as 500 `INTERNAL_ERROR` so the
 *   client always sees a consistent body.
 */
export default fastifyPlugin((fastify: BaseFastifyInstance) => {
  fastify.setErrorHandler(
    (err: unknown, req: BaseFastifyRequest, reply: BaseFastifyReply) => {
      if (err instanceof BaseHttpError) {
        const body: ErrorReply = {
          code: err.code,
          message: err.message,
        };
        if (err.details !== undefined) body.details = err.details;
        return reply.code(err.statusCode).send(body);
      }

      const frameworkStatus = (err as { statusCode?: unknown }).statusCode;
      const frameworkBody =
        typeof frameworkStatus === 'number'
          ? FRAMEWORK_ERRORS[frameworkStatus]
          : undefined;
      if (frameworkBody !== undefined) {
        return reply.code(frameworkStatus as number).send(frameworkBody);
      }

      req.log.info({
        msg: 'Request encountered an unexpected error',
        err,
      });

      const fallback: ErrorReply = {
        code: 'INTERNAL_ERROR',
        message:
          'Server encountered an unexpected error. Please try again later.',
      };
      return reply.code(500).send(fallback);
    },
  );
});
