name: Python CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      transcription_service: ${{ steps.filter.outputs.transcription_service }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            transcription_service:
              - 'transcription_service/**'

  format:
    needs: changes
    if: needs.changes.outputs.transcription_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Check formatting
        working-directory: "transcription_service"
        run: make format

  lint:
    needs: changes
    if: needs.changes.outputs.transcription_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Run linter
        working-directory: "transcription_service"
        run: make lint

  test:
    needs: changes
    if: needs.changes.outputs.transcription_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Run tests
        working-directory: "transcription_service"
        run: make test

      - name: Code Coverage Report - Transcription Service
        uses: ./.github/actions/coverage-report
        with:
          package_name: "Transcription Service"
          filename: "./transcription_service/coverage.xml"

  docker-build-transcription-service:
    needs: [changes, test]
    if: needs.changes.outputs.transcription_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build transcription-service CPU Docker image
        uses: ./.github/actions/build-container
        with:
          image_name: scribear/transcription-service-cpu
          build_context: transcription_service
          dockerfile: transcription_service/Dockerfile_CPU
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build transcription-service CUDA Docker image
        uses: ./.github/actions/build-container
        with:
          image_name: scribear/transcription-service-cuda
          build_context: transcription_service
          dockerfile: transcription_service/Dockerfile_CUDA
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
